// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcYIuc1bT3m8zvyyeDOuhjG9HJnEIV1JY',
    appId: '1:253004948138:web:861697f490f21913a2e6d3',
    messagingSenderId: '253004948138',
    projectId: 'rl-express-partner',
    authDomain: 'rl-express-partner.firebaseapp.com',
    storageBucket: 'rl-express-partner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyqqR2gVtJXwFWw99UnwjBqUihg8W-zA',
    appId: '1:253004948138:android:ca960e425cc10624a2e6d3',
    messagingSenderId: '253004948138',
    projectId: 'rl-express-partner',
    storageBucket: 'rl-express-partner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa9re8YZzGmn9tHcYMRrPDOVBr_7mCBAs',
    appId: '1:253004948138:ios:d0d3e7b95ecc7528a2e6d3',
    messagingSenderId: '253004948138',
    projectId: 'rl-express-partner',
    storageBucket: 'rl-express-partner.firebasestorage.app',
    iosBundleId: 'cm.rlexpress.rlExpressPartner',
  );
}
